### ISSUE TITLE
Omeka in Google Chrome

### ISSUE THREAD

**Issue by pricemtchemp** [AppStateLibrary/omeka#16]
Omeka is showing formatting and functionality issues in Google Chrome.

**Comment by ksclarke** [comment]
Thanks Pam, could you include a screenshot?

**Comment by ricedm** [comment]
It works in some versions of Chrome. I have 40.0.2214.111 and it is totally broken.
![screen shot 2015-02-12 at 12 47 44 pm](https://cloud.githubusercontent.com/assets/10980583/6173364/6723536a-b2b5-11e4-98fc-49bf8f3e7482.png)

**Comment by ksclarke** [comment]
Thanks. Turns out I didn't even need the screenshot as I'm a Chrome user, too, and see the problem now that I'm back looking at the site again.  I'll go see if I can determine what's changed on the server.

**Comment by ksclarke** [comment]
Disabling gzip with "SetEnv no-gzip 1" in the Apache configuration fixes the problem.
