### ISSUE TITLE
Odd records--possibly search function issues

### ISSUE THREAD

**Issue by pricemtchemp** [AppStateLibrary/omeka#21]
There are some strange records in Omeka such as these two,

http://omeka.library.appstate.edu/files/show/10873
http://omeka.library.appstate.edu/files/show/11810

I checked the same search in Chrome (Greta used firefox) with identical issues by searching "shield" in the 
search box on the Digital Collections page.

I then found the items directly through 1. title and 2. item ID#. The items display correctly in omeka. The issue 
is the search results links. The first link displays an item from The Appalachian Student Newspaper, but its 
actul ID# is different than the one listed in the link. The ID listed in the link brings up a photograph in omeka. 

I think the search function in omeka is off. It seems to be combining items/data.

**Comment by ksclarke** [comment]
This is fixed with Solr only displaying items (not files):

http://axis001.library.appstate.edu:8081/solr-search?q=%22Voters+Approve+Bond+Issues%22

This fix will be moved to the production site when we push the latest dev changes over.
