### ISSUE TITLE
Upgrade omeka-dev to latest version

### ISSUE THREAD

**Issue by ksclarke** [AppStateLibrary/omeka#42]
Q: actually upgrade or point to new dev site?

**Comment by ksclarke** [comment]
We need to extract the faculty projects which are really production content. There is a new ticket for this (#46) so that we can update the new site (or point dev to the new dev site).

**Comment by ksclarke** [comment]
@ransomww Now that we've moved faculty projects I can reset omeka-dev so that it's a current snapshot with the latest code, but I wanted to confirm with you that folks are using the faculty projects site now instead of omeka-dev still before doing that. Are we okay to wipe omeka-dev and update it's code?

**Comment by ransommw** [comment]
Not yet. We still have to contact a few faculty about the change over.

**Comment by ksclarke** [comment]
Okay, no problem. If you'd just let me know on this ticket when the full migration is ready to happen. Thanks.

**Comment by ransommw** [comment]
I think is is ok to go ahead with the full migration now. Thanks.

**Comment by ksclarke** [comment]
Updated omeka-dev to the current version of Omeka that is used on staging and production.
