### ISSUE TITLE
File names for A/V icons on item page

### ISSUE THREAD

**Issue by ransommw** [AppStateLibrary/omeka#47]
In omeka.library.appstate.edu, the attached file icons show an omeka generated numeric file name while hovering over. Is it possible to keep the original file name so we know what the file is or be able to name each file on the item page? As it is now, we are not able to discern what each file is in public view when there are multiple files on the item page.

**Comment by ksclarke** [comment]
Yes, it looks like at some point someone wrote some Javascript that hides the file name with "Download PDF" or "Listen to sound file". We could remove that and the file name would be displayed again. For example, see: http://omeka.library.appstate.edu:8081/items/show/33656

Would you want the name of the file included with the instruction "Download PDF" or just have the file name by itself?

Would you want a little padding to separate the file name from the line that separates the two columns of the item page?

**Comment by ransommw** [comment]
Is it possible to make this change ONLY for audio files and leave the PDFs that way they are? We only need the change to be able to put multiple audio tracks on the same item page.

Yes, a little buffer from the column line would be good. Considering the audio icon, we don't really need a listen to audio instruction.

**Comment by ksclarke** [comment]
Yes, it can be made just for audio files. Thanks. Could you give me a link to an audio record that should get the change?

**Comment by ransommw** [comment]
Here you go:
http://omeka.library.appstate.edu/items/show/41694
There is one 45 minute file there now. We have split that file into 15 smaller files that all need to go on the same item page. Thanks.

**Comment by ksclarke** [comment]
Could you let me know when that's done (or point me to another example that already has a bunch of files)?

**Comment by ransommw** [comment]
Here you go:

http://omeka.library.appstate.edu/items/show/41694

I just uploaded all the files for that page.

**Comment by ransommw** [comment]
Any luck with this?

**Comment by ksclarke** [comment]
Haven't gotten to it but I do plan to have some time this weekend to work on it.

**Comment by ksclarke** [comment]
@ransommw How is this? It's not yet in production just on the link below.

http://omeka.library.appstate.edu:8081/items/show/41694

**Comment by ransommw** [comment]
That looks great.

**Comment by ksclarke** [comment]
Fixed with #49
