### ISSUE TITLE
Items not showing all populated metadata fields

### ISSUE THREAD

**Issue by ransommw** [AppStateLibrary/omeka#51]
On a new collection being uploaded via .csv, only 4 of 10 populated metadata fields are showing in the public view. The edit view shows all 10 fields correctly. It is ignoring all of the item type metadata and some Dublin Core fields.
Example here:
http://omeka.library.appstate.edu/items/show/42776

This is the same collection with the PDF viewer problem.

**Comment by ransommw** [comment]
It seems to be just the "still image" item type that is having this problem. 
I reinserted the collection as "document" item type and had no display issues.

**Comment by ksclarke** [comment]
This link above is a 404 for me. Do you have another example?

**Comment by ransommw** [comment]
I had to redo the collection to work around the problem, so the link is dead. Here is another example:
http://omeka.library.appstate.edu/admin/items/show/364
In the EDIT view, Geographic Location and Physical Dimensions show properly with element content.
In the PUBLIC view, those two elements are missing.
